import * as fs from "fs";
import * as path from "path";

interface SkillData {
  slug: string;
  phase: number;
  title: string;
  description: string;
  triggers: string;
  methodology: string;
  instructions: string;
  examples: string;
  references: string;
}

const CONTENT_DIR = path.join(process.cwd(), "content", "skills");
const OUTPUT_FILE = path.join(process.cwd(), "src", "lib", "skills-data.ts");

function parseSkillMd(content: string): Omit<SkillData, "slug" | "phase"> {
  // Normalize line endings
  const text = content.replace(/\r\n/g, "\n");

  // Section names to look for (case-insensitive)
  const sectionNames = [
    "Description",
    "Triggers",
    "Methodology",
    "Instructions",
    "Examples",
    "References",
  ];

  // Build regex that matches both "## Section" and bare "Section" at start of line
  // We capture everything between section headers
  const sectionRegex = new RegExp(
    `^(?:#{1,2}\\s+)?(${sectionNames.join("|")})\\s*$`,
    "gmi"
  );

  const sections: Record<string, string> = {};
  const matches: { name: string; index: number }[] = [];

  // Extract title from first line (with or without #)
  const firstLine = text.split("\n")[0].replace(/^#\s+/, "").trim();

  let match;
  while ((match = sectionRegex.exec(text)) !== null) {
    matches.push({ name: match[1].toLowerCase(), index: match.index });
  }

  for (let i = 0; i < matches.length; i++) {
    const start = text.indexOf("\n", matches[i].index) + 1;
    const end = i + 1 < matches.length ? matches[i + 1].index : text.length;
    sections[matches[i].name] = text.slice(start, end).trim();
  }

  return {
    title: firstLine,
    description: sections["description"] || "",
    triggers: sections["triggers"] || "",
    methodology: sections["methodology"] || "",
    instructions: sections["instructions"] || "",
    examples: sections["examples"] || "",
    references: sections["references"] || "",
  };
}

function main() {
  const dirs = fs
    .readdirSync(CONTENT_DIR)
    .filter((d) => fs.statSync(path.join(CONTENT_DIR, d)).isDirectory())
    .sort();

  const skills: SkillData[] = [];

  for (const dir of dirs) {
    const skillFile = path.join(CONTENT_DIR, dir, "SKILL.md");
    if (!fs.existsSync(skillFile)) continue;

    const content = fs.readFileSync(skillFile, "utf-8");
    const parsed = parseSkillMd(content);

    // Extract phase from directory name prefix (e.g., "00-", "01-", "02-")
    const phaseMatch = dir.match(/^(\d{2})-/);
    const phase = phaseMatch ? parseInt(phaseMatch[1], 10) : 0;

    skills.push({
      slug: dir,
      phase,
      ...parsed,
    });
  }

  // Generate TypeScript file
  const output = `// Auto-generated by scripts/parse-skills.ts — DO NOT EDIT
import { Skill } from "@/types/skill";

export const skills: Skill[] = ${JSON.stringify(skills, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`Parsed ${skills.length} skills → ${OUTPUT_FILE}`);
}

main();
